local_default: &local_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

deploy_default: &deploy_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *local_default
  database: colorado-benefits_development

test:
  <<: *local_default
  database: colorado-benefits_test

staging:
  <<: *deploy_default

production:
  <<: *deploy_default

demo:
  <<: *deploy_default
